services:
  nuxt-dockerize-example:
    environment:
      - NUXT_PUBLIC_APPLICATION_NAME=nuxt-dockerize-example-docker-container-nuxi
      - NUXT_SECRET=c6b20183-be1e-4020-9c0a-85bef1cc5b8a
    build:
      context: .
    container_name: nuxt-dockerize-example-nuxi
    ports:
      - 3000:3000
    restart: always