services:
  nuxt-dockerize-example:
    environment:
      - APPLICATION_NAME=nuxt-dockerize-example-docker-container-nuxt-bridge-broken
      - SECRET=c6b20183-be1e-4020-9c0a-85bef1cc5b8a
    build:
      context: .
    container_name: nuxt-dockerize-example-nuxt-bridge-broken
    ports:
      - 3002:3000
    restart: always